server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivekpegasusone/config-store.git
          search-paths:
            - 'service-config/*service'
          #uri: https://github.com/vivekpegasusone/spring-cloud-config-store
          #search-paths:
          #  - '*service'
          #username: vivekpegasusone
          #password: